### ISSUE TITLE
Using trimage on linux server edition

### ISSUE THREAD

**Issue by eberfreitas** [Kilian/Trimage#14]
Hey guys!

First of all, thanks for this awesome tool! It's really good :)

I'm trying to use it on my web app and it runs on Ubuntu Lucid 64bit Server Edition. When I try to run it, I get the following error message:

```
trimage.py: cannot connect to X server
```

Is there a way to install this dependecty and start to work with it? Or is there another way? Thanks mates!

**Comment by gogo125** [comment]
Here are the steps I took to get this working:
**To Install:**
sudo apt-get install trimage
sudo apt-get install xvfb
sudo apt-get install libpng-dev

**To Run:**
/usr/bin/xvfb-run -a trimage theImage.png

In the end however, I stuck with just using optipng and jpegoptim instead as there wasn't much of a compression gain.

**Comment by Blueblazer172** [comment]
> Here are the steps I took to get this working:
> **To Install:**
> sudo apt-get install trimage
> sudo apt-get install xvfb
> sudo apt-get install libpng-dev
> 
> **To Run:**
> /usr/bin/xvfb-run -a trimage theImage.png
> 
> In the end however, I stuck with just using optipng and jpegoptim instead as there wasn't much of a compression gain.

yep worked for me this way. Thanks !
