### ISSUE TITLE
CentOS 6 - PyQt4.QtCore import * error

### ISSUE THREAD

**Issue by mhamzas** [Kilian/Trimage#31]
Hi all,
I have just installed trimage on centos 6 and i got this when running the following command.
# trimage -v

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/trimage/trimage.py", line 14, in <module>
    from PyQt4.QtCore import *
ImportError: No module named PyQt4.QtCore

**Comment by Huluti** [comment]
Could be closed I think since the first issue is solved @Kilian
