### ISSUE TITLE
Add mozjpeg support for jpeg lossless compression

### ISSUE THREAD

**Issue by pauloxnet** [Kilian/Trimage#32]
Can you add [mozjpeg](https://github.com/mozilla/mozjpeg) for better jpeg lossless compression as reported in this comparison :
[Comparison of JPEG Lossless Compression Tools](http://blarg.co.uk/blog/comparison-of-jpeg-lossless-compression-tools)

**Comment by logos88** [comment]
This would improve the compression for sure

**Comment by Kilian** [comment]
Mozjpeg is not included in Ubuntu, afaik, so we can't request is as dependency and would have to bundle it, if the license allows it. PR welcome.

**Comment by logos88** [comment]
In the Arch package in aur should be easier to add it like a dependency, or optional dependency
https://aur.archlinux.org/packages/trimage/

**Comment by outbacker** [comment]
Soo...has this been closed because mozjpeg is supported now? Or was the idea abandoned?

**Comment by Kilian** [comment]
PRs still welcome :)
