### ISSUE TITLE
EXIF metadata Dumped

### ISSUE THREAD

**Issue by jujumo** [Kilian/Trimage#33]
I just try trimage, and was really exited by its potential.
Unfortunatly, I cannot use it beacuse it drops most of the EXIFS metadata (see it with exiftool).
Its probabliy due to the way jpegoptim works.
Buts sincce youre wrapping around it, maybe you can also use exiftool to also copy metadata into the new optimized file ?

Regards,
Julien

**Comment by Kilian** [comment]
Trimage is made to optimize images for websites/online usage, where EXIF isn't needed. If you want to compress images but keep the exif data, please use another tool

**Comment by jujumo** [comment]
Thanks for your answer. It make sense. But, at least, you may warms users (dumb like me) that are tempted to use it to gain disk space.

**Comment by jujumo** [comment]
OK, thanks. I should have read that If I spent more time to read the description. Sorry for the inconvienance.

**Comment by Kilian** [comment]
FWIW, we're considering adding a big warning on first startup
