### ISSUE TITLE
Support SVG compression

### ISSUE THREAD

**Issue by jancborchardt** [Kilian/Trimage#35]
I use trimage a bunch for ownCloud icons (thx @Kilian ;) – one problem is that I still need to compress SVG icons manually using the console and scour:
```
scour -i $svg.opttmp -o $svg --create-groups --enable-id-stripping --enable-comment-stripping --shorten-ids --remove-metadata;
```
Would be awesome if Trimage could support SVG out of the box so I can just easily drag-n-drop like with PNGs.

**Comment by Kilian** [comment]
scour is really cool and i like the idea of SVG compression, but scour is lossy it seems, and Trimage is explicitly not so. Would it be possible to have SVG compression in scour without it rewriting the actual "image" data?

**Comment by jancborchardt** [comment]
The web service Compressor.io also uses Scour: https://compressor.io/about – not sure if there’s a lossless app.

Does using Scour with less flags result in it being less lossy maybe? I have no idea about the internals either.

**Comment by johandouma** [comment]
SVGO is lossless. But I'm not sure how easy it would be to integrate npm packages.

**Comment by jancborchardt** [comment]
At least in the past we had some issues with svgo when using it for Nextcloud icons as it changed shapes sometimes.

Don't remember if that was related to some flags, but something to look out for.
