### ISSUE TITLE
Support pngout as PNG compressor

### ISSUE THREAD

**Issue by meonwax** [Kilian/Trimage#40]
Hi,

would it be possible to use [pngout](http://advsys.net/ken/utils.htm) by Ken Silverman to reduce the filesize of PNGs even further?

[Here](http://blog.codinghorror.com/getting-the-most-out-of-png) is a (rather old) blogpost about the little program.

Cheers

**Comment by meonwax** [comment]
Here is the Linux port:
http://www.jonof.id.au/pngout

It seems that it is only availbale in binary form.

**Comment by Kilian** [comment]
I'd like to, but with the licensing of PNGOUT it is iffy, as it's not open source. So no plans.
