### ISSUE TITLE
Getting No module named trimage error

### ISSUE THREAD

**Issue by shawnbro** [Kilian/Trimage#46]
Just installed using apt-get and get the following error:

<img width="698" alt="screen shot 2017-08-29 at 11 19 59 am" src="https://user-images.githubusercontent.com/6208719/29837084-0ee2d10c-8cac-11e7-8c2f-530a7188ab29.png">

**Comment by Kilian** [comment]
hi @shawnbro which distribution are you using? what happens when you type "which trimage"?

**Comment by shawnbro** [comment]
thanks @Kilian i believe i'm using this distribution: `trimage_1.0.5-1.1_all.deb`

when i type `which trimage` i get this: `/app/.apt/usr/bin/trimage`

**Comment by shawnbro** [comment]
oops my bad. Ubuntu 16.04.  i'm using a heroku buildpack so that's why it's constructed that way.  what i think is it might be trying to load the module but can't find it  because it's not in the path.

**Comment by Kilian** [comment]
I think it's indeed trimage.py that's missing from path. I'd check with Heroku for how they organise this stuff.

**Comment by shawnbro** [comment]
yes! adding the `trimage` dir to the python path did solve that issue.  now i'm getting `No module named PyQt4.QtCore` prob the same problem?

**Comment by shawnbro** [comment]
led to too many other deps missing. i don't think it will work because it's heroku and i lack the ability to configure the server as i should.  closing this issue now.  thanks.
