### ISSUE TITLE
Can't build it from AUR. Phonon 4 --> Unknown Public Key 

### ISSUE THREAD

**Issue by Rencer** [Kilian/Trimage#54]
I using the Arch-based Manjaro Linux.
I tried to build Trimage from the AUR (using the yaourt command), but when it tries to build the Phonon-4.10.1 and it is verifying source file signatures with gpg, it fails. It gives an "unknown public key" error.

I already searched for answers in the Manjaro forum, and I find this:
[https://forum.manjaro.org/t/solved-update-fails-partially-on-phonon-qt4/56174](url)
In short, this is the "answer" to this problem:
"...most likely you don’t need it at all and better to remove it."
Really? Just remove it, because the Manjaro team decided to not support the package anymore? So how I can use those programs that need this phonon 4 package? Nevermind...

I also find some posts about this same error on different Linux pletforms, but the answer was always the same; "remove it"...
So, I don't find anything that can help, only just these useless "remove it" posts...

I like to ask you guys, how I can resolve this problem?
I know that this program is a GUI for some command-line image optimization tools, but I really need a GUI for faster work, because I need to optimize thousands of files.

**Comment by Huluti** [comment]
Trimage will use Python3 and Qt5 in the next version that will be out shortly. No more need for the phonon-qt4 package.

**Comment by Rencer** [comment]
Thanks.
