### ISSUE TITLE
Interest in supporting Flatpak or COPR

### ISSUE THREAD

**Issue by phillipsj** [Kilian/Trimage#58]
Is there any interest in supporting Flatpak. I have moved to Fedora and I don't see any packages readily available for it.  I would be happy to create it if it was something desired.

**Comment by Huluti** [comment]
For sure. It will be interesting when Trimage 1.0.6 will be available in a few days with Python3, Qt5 and some fixes.

**Comment by Kilian** [comment]
Yes please! I'm about ready with the debian folder, so if you could give it a go that would be great.

**Comment by phillipsj** [comment]
Cool, I will get a PR started. This will be a first for me, but I enjoy the project and I would like it to be available for more people.

**Comment by Wdavery** [comment]
Would love to see this!

**Comment by Huluti** [comment]
@phillipsj any news about the flatpak package?

**Comment by phillipsj** [comment]
Yeah sorry, life has gotten in the way.  So I have the basics in place, the
one issue I have is trying to get the advpng dependency to build. I haven't
had much experience with building C applications to figure out what it
keeps failing. I will get back on this and try to find some help.

https://github.com/phillipsj/Trimage/blob/feature/flatpak/org.trimage.Trimage.json

**Comment by phillipsj** [comment]
Good news, I have made it past all of the depedencies, now I just need to work through the actual trimage build and install.

**Comment by Huluti** [comment]
@phillipsj that's good news ;)

**Comment by phillipsj** [comment]
Awesome!

**Comment by zendre4** [comment]
+1 for flatpak
