### ISSUE TITLE
Remove all ICC-Profiles

### ISSUE THREAD

**Issue by filetime** [Kilian/Trimage#61]
I suggest to strip all ICC-Profiles because they are useless. No browser supports any Color-Management and some older IEs even cannot display images with a profile. ICC-Profiles are very  common when you work with professional Print-Publishers and many modern profiles are very  complex to save ink and will be larger than the images itself.

If you think that Trimage then no longer will be lossless, think of the Metadata. You strip them too, they are lost? Another idea would be to make this as an option.

**Comment by Kilian** [comment]
Had a quick look. For jpegs, we already strip ICC using `--strip-all` in `jpegoptim` and for PNG we remove them with `-rem iCCP` in `pngcrush`. Are there instances where this is not happening for you?

**Comment by filetime** [comment]
Thanks for quick answer. Yes, i have some optimized images which seem to a profile when examined with Exiftool. But will check jpegoptim.

**Comment by filetime** [comment]
Thanks, it seems my copy of jpegoptim was mesed up.
