### ISSUE TITLE
No option to choose resulting file size....

### ISSUE THREAD

**Issue by njhetherington** [Kilian/Trimage#68]

**Comment by njhetherington** [comment]
Why is this closed ?

**Comment by Kilian** [comment]
Trimage is a tool to compress images to the smallest possible file size without affecting quality. "Choosing file size" would be antithetical to its purpose.

**Comment by 9mm** [comment]
Lmao, roasted.

@Kilian what about an option to pass flags to the libraries you use? For example jpegoptim allows for a --quality flag for cases where optimization + lossless is OK. I realize that's not the real core intention of the library which is lossless, but then it at least allows compressing multiple formats like imageoptim does (which also has various jpg/png quality options)
