### ISSUE TITLE
Use pngquant over pngcrush

### ISSUE THREAD

**Issue by skorokithakis** [Kilian/Trimage#75]
pngquant [seems to give better results](https://pointlessramblings.com/posts/pngquant_vs_pngcrush_vs_optipng_vs_pngnq/) than pngcrush, is it possible to use that, or at least use both and pick?

**Comment by Kilian** [comment]
Pngquant gives better results because it has lossy compression. Trimage only does lossless compression so there's no risk of creating worse quality images. So unfortunately Pngquant is not compatibly with Trimage's goals.
